from pathlib import Path

from contractguard.models import ContractReport


def render_markdown_report(report: ContractReport) -> str:
    lines = [
        "# ContractGuard API Compatibility Report",
        "",
        f"**Old Spec:** {report.old_title}",
        f"**New Spec:** {report.new_title}",
        f"**Result:** {report.result}",
        f"**Risk Level:** {report.risk_level}",
        f"**Breaking Changes:** {report.breaking_count}",
        "",
    ]

    if not report.changes:
        lines.extend([
            "## Summary",
            "",
            "No breaking API contract changes were detected.",
            "",
        ])
        return "\n".join(lines)

    lines.extend(["## Detected Changes", ""])

    for index, change in enumerate(report.changes, start=1):
        lines.extend([
            f"### {index}. {change.category}",
            "",
            f"- **Severity:** {change.severity}",
            f"- **Location:** `{change.location}`",
            f"- **Issue:** {change.message}",
            f"- **Recommended Action:** {change.recommendation}",
            "",
        ])

    lines.extend([
        "## Release Guidance",
        "",
        "If this report fails, review whether the API change should be restored, made backward-compatible, or released under a new version.",
        "",
        "Generated by ContractGuard.",
        "",
    ])
    return "\n".join(lines)


def write_markdown_report(report: ContractReport, output_path: str | Path) -> Path:
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_markdown_report(report), encoding="utf-8")
    return path
